#!/usr/bin/env python3
"""
One-shot model setup for LunaVox.

Runtime artifacts generated by this pipeline:

- models/qwen3_tts_talker.q5_k.gguf
- models/qwen3_tts_predictor.q8_0.gguf
- models/qwen3_tts_codec_encoder.fp16.onnx
- models/qwen3_tts_speaker_encoder.fp16.onnx
- models/qwen3_tts_decoder.fp16.onnx
- models/embeddings/*
- models/tokenizer.json
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterable, Optional

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLS_DIR = REPO_ROOT / "tools"

BASE_REPO_IDS = [
    "Qwen/Qwen3-TTS-12Hz-0.6B-Base",
    "Qwen/Qwen3-TTS-0.6B-Base",
]
TOKENIZER_REPO_IDS = [
    "Qwen/Qwen3-TTS-Tokenizer-12Hz",
]


def eprint(msg: str) -> None:
    print(msg, file=sys.stderr)


def run_cmd(
    cmd: list[str],
    cwd: Path,
    env: Optional[dict[str, str]] = None,
    timeout_sec: Optional[int] = None,
    log_file: Optional[Path] = None,
) -> None:
    eprint(f"[run] {' '.join(cmd)}")
    start = time.time()
    output_text = ""
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            check=True,
            env=env,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout_sec if timeout_sec and timeout_sec > 0 else None,
        )
        output_text = proc.stdout or ""
    except subprocess.TimeoutExpired as err:
        output_text = ""
        if err.stdout:
            output_text += err.stdout if isinstance(err.stdout, str) else err.stdout.decode("utf-8", errors="ignore")
        if err.stderr:
            output_text += err.stderr if isinstance(err.stderr, str) else err.stderr.decode("utf-8", errors="ignore")
        if log_file:
            log_file.parent.mkdir(parents=True, exist_ok=True)
            log_file.write_text(
                f"[timeout] {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
                f"cmd: {' '.join(cmd)}\n"
                f"cwd: {cwd}\n"
                f"timeout_sec: {timeout_sec}\n\n"
                f"{output_text}",
                encoding="utf-8",
            )
        msg = f"Command timed out after {timeout_sec}s: {' '.join(cmd)}"
        if log_file:
            msg += f"\nSee log: {log_file}"
        raise RuntimeError(msg) from err
    except subprocess.CalledProcessError as err:
        output_text = err.stdout or ""
        if log_file:
            log_file.parent.mkdir(parents=True, exist_ok=True)
            log_file.write_text(
                f"[failed] {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
                f"cmd: {' '.join(cmd)}\n"
                f"cwd: {cwd}\n"
                f"returncode: {err.returncode}\n\n"
                f"{output_text}",
                encoding="utf-8",
            )
        raise

    if log_file:
        elapsed = time.time() - start
        log_file.parent.mkdir(parents=True, exist_ok=True)
        log_file.write_text(
            f"[ok] {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
            f"cmd: {' '.join(cmd)}\n"
            f"cwd: {cwd}\n"
            f"elapsed_sec: {elapsed:.3f}\n\n"
            f"{output_text}",
            encoding="utf-8",
        )


def has_module(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


def require_modules(modules: Iterable[tuple[str, str]]) -> None:
    missing = [f"{name} ({pip_name})" for name, pip_name in modules if not has_module(name)]
    if missing:
        raise RuntimeError(
            "Missing required Python modules: "
            + ", ".join(missing)
            + "\nInstall them, for example:\n"
            + f"  {sys.executable} -m pip install "
            + " ".join(pip_name for _, pip_name in modules)
        )


def snapshot_download_repo(
    repo_ids: list[str],
    local_dir: Path,
    token: Optional[str],
    allow_patterns: Optional[list[str]],
) -> None:
    from huggingface_hub import snapshot_download

    local_dir.mkdir(parents=True, exist_ok=True)
    last_err: Optional[Exception] = None
    for repo_id in repo_ids:
        try:
            eprint(f"[download] {repo_id} -> {local_dir}")
            snapshot_download(
                repo_id=repo_id,
                local_dir=str(local_dir),
                token=token,
                allow_patterns=allow_patterns,
                resume_download=True,
            )
            return
        except Exception as err:
            last_err = err
            eprint(f"[warn] failed to download {repo_id}: {err}")

    if last_err is not None:
        raise last_err
    raise RuntimeError("No model repositories configured")


def ensure_base_assets(base_dir: Path, token: Optional[str], force_download: bool) -> None:
    required = [
        base_dir / "config.json",
        base_dir / "model.safetensors",
        base_dir / "vocab.json",
        base_dir / "merges.txt",
        base_dir / "tokenizer_config.json",
    ]

    if force_download and base_dir.exists():
        eprint(f"[clean] removing {base_dir}")
        shutil.rmtree(base_dir)

    if all(p.exists() for p in required):
        eprint(f"[ok] base assets already present in {base_dir}")
        return

    allow_patterns = [
        "config.json",
        "generation_config.json",
        "model.safetensors",
        "tokenizer_config.json",
        "vocab.json",
        "merges.txt",
        "preprocessor_config.json",
        "speech_tokenizer/*",
    ]
    snapshot_download_repo(BASE_REPO_IDS, base_dir, token, allow_patterns)


def ensure_tokenizer_assets(
    base_dir: Path,
    tokenizer_dir: Path,
    token: Optional[str],
    force_download: bool,
) -> Path:
    in_base = base_dir / "speech_tokenizer" / "model.safetensors"
    if in_base.exists():
        eprint("[ok] using tokenizer assets from base repo (speech_tokenizer/)")
        return base_dir

    if force_download and tokenizer_dir.exists():
        eprint(f"[clean] removing {tokenizer_dir}")
        shutil.rmtree(tokenizer_dir)

    req_tok = [tokenizer_dir / "config.json", tokenizer_dir / "model.safetensors"]
    if not all(p.exists() for p in req_tok):
        allow_patterns = [
            "config.json",
            "configuration.json",
            "model.safetensors",
            "preprocessor_config.json",
        ]
        snapshot_download_repo(TOKENIZER_REPO_IDS, tokenizer_dir, token, allow_patterns)

    return tokenizer_dir


def ensure_talker_predictor(
    python_exe: str,
    base_dir: Path,
    out_talker: Path,
    out_predictor: Path,
    out_embeddings_dir: Path,
) -> None:
    if out_talker.exists() and out_predictor.exists():
        eprint(f"[ok] exists: {out_talker}")
        eprint(f"[ok] exists: {out_predictor}")
        return

    run_cmd(
        [
            python_exe,
            str(TOOLS_DIR / "conversion" / "convert_talker_predictor_llama.py"),
            "--input",
            str(base_dir),
            "--out-talker",
            str(out_talker),
            "--out-predictor",
            str(out_predictor),
            "--embeddings-dir",
            str(out_embeddings_dir),
        ],
        cwd=REPO_ROOT,
    )


def ensure_embeddings(
    python_exe: str,
    base_dir: Path,
    out_embeddings_dir: Path,
) -> None:
    text_emb = out_embeddings_dir / "text_embedding_projected.npy"
    codec_emb0 = out_embeddings_dir / "codec_embedding_0.npy"
    if text_emb.exists() and codec_emb0.exists():
        eprint(f"[ok] exists: {out_embeddings_dir}")
        return
    run_cmd(
        [
            python_exe,
            str(TOOLS_DIR / "conversion" / "export_embeddings.py"),
            "--input",
            str(base_dir),
            "--output",
            str(out_embeddings_dir),
        ],
        cwd=REPO_ROOT,
    )


def ensure_tokenizer_json(base_dir: Path, out_tokenizer_json: Path) -> None:
    src = base_dir / "tokenizer.json"
    out_tokenizer_json.parent.mkdir(parents=True, exist_ok=True)
    if src.exists():
        shutil.copy2(src, out_tokenizer_json)
        return
    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(str(base_dir), trust_remote_code=True, fix_mistral_regex=True)
    if not hasattr(tok, "backend_tokenizer"):
        raise RuntimeError("Tokenizer backend is unavailable; failed to generate tokenizer.json")
    tok.backend_tokenizer.save(str(out_tokenizer_json))


def run_onnx_stage(
    python_exe: str,
    stage: str,
    base_dir: Path,
    models_dir: Path,
    timeout_sec: int,
    logs_dir: Path,
    enable_quant: bool,
) -> None:
    log_file = logs_dir / f"{stage}.log"
    env = os.environ.copy()
    env["PYTHONUTF8"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"
    cmd = [
        python_exe,
        str(TOOLS_DIR / "conversion" / "export_onnx_models.py"),
        "--base-dir",
        str(base_dir),
        "--output-dir",
        str(models_dir),
        "--stage",
        stage,
    ]
    if enable_quant:
        cmd.append("--enable-quant")
    run_cmd(
        cmd,
        cwd=REPO_ROOT,
        env=env,
        timeout_sec=timeout_sec,
        log_file=log_file,
    )


def ensure_onnx_artifacts(
    python_exe: str,
    base_dir: Path,
    models_dir: Path,
    out_codec_encoder: Path,
    out_speaker_encoder: Path,
    out_decoder: Path,
    timeout_sec: int,
    logs_dir: Path,
    enable_quant: bool,
) -> None:
    stage_to_output = {
        "codec_encoder": out_codec_encoder,
        "speaker_encoder": out_speaker_encoder,
        "decoder": out_decoder,
    }

    logs_dir.mkdir(parents=True, exist_ok=True)
    for stage, artifact in stage_to_output.items():
        if artifact.exists():
            eprint(f"[skip] ONNX stage '{stage}' already done: {artifact}")
            continue
        run_onnx_stage(
            python_exe=python_exe,
            stage=stage,
            base_dir=base_dir,
            models_dir=models_dir,
            timeout_sec=timeout_sec,
            logs_dir=logs_dir,
            enable_quant=enable_quant,
        )

    if enable_quant:
        run_onnx_stage(
            python_exe=python_exe,
            stage="quantize",
            base_dir=base_dir,
            models_dir=models_dir,
            timeout_sec=timeout_sec,
            logs_dir=logs_dir,
            enable_quant=enable_quant,
        )

    missing = [p for p in [out_codec_encoder, out_speaker_encoder, out_decoder] if not p.exists()]
    if missing:
        raise RuntimeError("ONNX export did not produce required files:\n" + "\n".join(str(p) for p in missing))

    run_cmd(
        [
            python_exe,
            str(TOOLS_DIR / "conversion" / "validate_onnx_models.py"),
            "--models-dir",
            str(models_dir),
        ],
        cwd=REPO_ROOT,
        timeout_sec=timeout_sec,
        log_file=logs_dir / "validate.log",
    )


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Download and prepare all runtime models for lunavox")
    p.add_argument("--models-dir", default=str(REPO_ROOT / "models" / "base_small"), help="Target models directory")
    p.add_argument("--hf-token", default=os.environ.get("HF_TOKEN", ""), help="HF token (or set HF_TOKEN)")
    p.add_argument("--skip-download", action="store_true", help="Skip model downloads")
    p.add_argument("--skip-convert", action="store_true", help="Skip artifact conversion/export")
    p.add_argument("--force", action="store_true", help="Re-download/re-generate outputs")
    p.add_argument("--timeout-sec", type=int, default=170, help="Per-stage timeout in seconds for ONNX export")
    p.add_argument(
        "--skip-quant",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Skip optional local ONNX int8 quantization stage (default: true)",
    )
    p.add_argument("--enable-quant", action="store_true", help="Alias of --no-skip-quant")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    enable_quant = bool(args.enable_quant or (not args.skip_quant))

    require_modules(
        [
            ("torch", "torch"),
            ("numpy", "numpy"),
            ("tqdm", "tqdm"),
            ("safetensors", "safetensors"),
            ("gguf", "gguf"),
            ("transformers", "transformers"),
        ]
    )
    if not args.skip_convert:
        require_modules(
            [
                ("onnx", "onnx"),
                ("onnxruntime", "onnxruntime"),
            ]
        )
        if enable_quant:
            require_modules([("onnxruntime.quantization", "onnxruntime-tools")])

    models_dir = Path(args.models_dir).resolve()
    base_dir = models_dir / "Qwen3-TTS-12Hz-0.6B-Base"
    tokenizer_dir = models_dir / "Qwen3-TTS-Tokenizer-12Hz"

    out_talker = models_dir / "qwen3_tts_talker.q5_k.gguf"
    out_predictor = models_dir / "qwen3_tts_predictor.q8_0.gguf"
    out_codec_encoder = models_dir / "qwen3_tts_codec_encoder.fp16.onnx"
    out_speaker_encoder = models_dir / "qwen3_tts_speaker_encoder.fp16.onnx"
    out_decoder = models_dir / "qwen3_tts_decoder.fp16.onnx"
    out_embeddings_dir = models_dir / "embeddings"
    out_tokenizer_json = models_dir / "tokenizer.json"
    logs_dir = REPO_ROOT / "logs" / "convert_onnx"

    hf_token = args.hf_token.strip() or None
    models_dir.mkdir(parents=True, exist_ok=True)

    if not args.skip_download:
        require_modules([("huggingface_hub", "huggingface_hub")])
        ensure_base_assets(base_dir, hf_token, args.force)
        ensure_tokenizer_assets(base_dir, tokenizer_dir, hf_token, args.force)

    if not args.skip_convert:
        if args.force:
            for p in [out_talker, out_predictor, out_codec_encoder, out_speaker_encoder, out_decoder, out_tokenizer_json]:
                if p.exists():
                    p.unlink()
            if out_embeddings_dir.exists():
                shutil.rmtree(out_embeddings_dir)

        ensure_talker_predictor(sys.executable, base_dir, out_talker, out_predictor, out_embeddings_dir)
        ensure_embeddings(sys.executable, base_dir, out_embeddings_dir)
        ensure_tokenizer_json(base_dir, out_tokenizer_json)
        ensure_onnx_artifacts(
            python_exe=sys.executable,
            base_dir=base_dir,
            models_dir=models_dir,
            out_codec_encoder=out_codec_encoder,
            out_speaker_encoder=out_speaker_encoder,
            out_decoder=out_decoder,
            timeout_sec=max(1, int(args.timeout_sec)),
            logs_dir=logs_dir,
            enable_quant=enable_quant,
        )

    eprint("\n[done] Model setup complete.")
    eprint(f"  - {out_talker}")
    eprint(f"  - {out_predictor}")
    eprint(f"  - {out_codec_encoder}")
    eprint(f"  - {out_speaker_encoder}")
    eprint(f"  - {out_decoder}")
    eprint(f"  - {out_embeddings_dir}")
    eprint(f"  - {out_tokenizer_json}")
    eprint("\nRun:")
    eprint("  ./build-cpu/qwen3-tts-cli -m models/base_small -t \"Hello\" -o out.wav")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
